modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "identity"
version = "${version}"
displayName = "Identity"
logoFile= "icon.png"
authors = "Draylar && Updated by Gaboouu"
description = '''
Play as your favorite entities!
No more crashes !!!
'''

[[dependencies.identity]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "identity.mixins.json"

[[mixins]]
config = "identity-forge.mixins.json"

[[mixins]]
config = "identity.alexsmobs.mixins.json"
