modLoader = "javafml"
loaderVersion = "[52,)"
license = "Custom"

[[mods]]
modId = "identity"
version = "${version}"
displayName = "Identity"
logoFile= "icon.png"
authors = "Draylar && Updated by Gaboouu"
description = '''
Play as your favorite entities!
No more crashes !!!
'''

[[dependencies.identity]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

